const PRIMARY_COLOR = '#303857';
const SECONDARY_COLOR = '#ffe200';
const PRIMARY_TEXT_COLOR = 'white';
const SECONDARY_TEXT_COLOR = 'black';

export {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  PRIMARY_TEXT_COLOR,
  SECONDARY_TEXT_COLOR,
};
