const PRIMARY_COLOR = 'white';
const SECONDARY_COLOR = '#68829E';
const PRIMARY_TEXT_COLOR = '#232F34';
const SECONDARY_TEXT_COLOR = 'white';

export {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  PRIMARY_TEXT_COLOR,
  SECONDARY_TEXT_COLOR,
};
