export const quizData = {
  all: [
    {id: 0, menu: 'all'},
    {id: 1, menu: 'pizza'},
    {id: 2, menu: 'pasta'},
    {id: 3, menu: 'hotdog'},
    {id: 4, menu: 'jesus'},
    {id: 5, menu: 'burrito'},
    {id: 6, menu: 'john'},
    {id: 7, menu: 'ramen'},
  ],
  best: [
    {id: 0, menu: 'best'},
    {id: 1, menu: 'pizza'},
    {id: 2, menu: 'pasta'},
    {id: 3, menu: 'hotdog'},
    {id: 4, menu: 'jesus'},
    {id: 5, menu: 'burrito'},
    {id: 6, menu: 'john'},
    {id: 7, menu: 'ramen'},
  ],
  new: [
    {id: 0, menu: 'new'},
    {id: 1, menu: 'pizza'},
    {id: 2, menu: 'pasta'},
    {id: 3, menu: 'hotdog'},
    {id: 4, menu: 'jesus'},
    {id: 5, menu: 'burrito'},
    {id: 6, menu: 'john'},
    {id: 7, menu: 'ramen'},
  ],
};
